ai4ch/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth import views as auth_views
from ckeditor_uploader import views as ckeditor_views
from django.views.static import serve  
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('beans/detect/', include('beans.api_urls', namespace='beans-api-detect')), 
    path('cassava/detect/', include('cassava.api_urls', namespace='cassava-api-detect')), 
    path('maize/detect/', include('maize.api_urls', namespace='maize-api-detect')), 
    path('rice/detect/', include('rice.api_urls', namespace='rice-api-detect')), 
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    # Include Django browsable API
    path('auth-api/', include('rest_framework.urls', namespace='rest_framework')),
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    # Application URLs
    path('', include('ai4chapp.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls', namespace='news')),
    path('beans/', include('beans.urls', namespace='beans')),   
    path('cassava/', include('cassava.urls', namespace='cassava')),
    path('maize/', include('maize.urls', namespace='maize')),
    path('rice/', include('rice.urls', namespace='rice')),
    path('reports/', include('reports.urls')),
    # Password reset views
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password/password_reset_complete.html'), name='password_reset_complete'),
    
    # Social authentication
    path('accounts/', include('allauth.urls')),
    
    # WYSIWYG editor
    path('tinymce/', include('tinymce.urls')),
    re_path(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    re_path(r'^ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import NewsAPIView
from django.conf import settings
from django.conf.urls.static import static

app_name = "news"

urlpatterns = [
    path("", NewsAPIView.news, name='news'),
    path('add-new/', NewsAPIView.add_new, name="add-new"),
    path('news-list/review-new/publish-new/<int:id>', NewsAPIView.publish_new, name="publish-new"),
    path('news-list/publish-new/<int:id>', NewsAPIView.publish_new, name="publish-new"),
    path('news-list/review-new/<int:id>', NewsAPIView.review_new, name="review-new"),
    path('news-list/view-new/<int:id>/', NewsAPIView.view_new, name="view-new"),
    path('news-list/delete-new/<int:id>/', NewsAPIView.delete_new, name="delete-new"),
    path('news-list/', NewsAPIView.news_list, name="news-list"),
    path('news/<str:slug>/', NewsAPIView.read_new, name="read-new"),
    path('<str:slug>/', NewsAPIView.read_new, name="read-new"),
    path('api/news', NewsAPIView.as_view(), name="news-api"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/system/pages/read_news.html
{% extends "../includes/master.html" %}
{% load static %}
{% block title %}AI4CH - News{% endblock %}
{% block content %}
    <!-- Start inner Page hero-->
    <section class="d-flex align-items-center page-hero  inner-page-hero " id="page-hero" style="margin-top:100px;">
      <div class="overlay-photo-image-bg parallax" data-bg-img="{% static 'assets/images/hero/inner-page-hero.jpg' %}" data-bg-opacity="1"></div>
      <div class="overlay-color" data-bg-opacity=".75"></div>
      <div class="container">
        <div class="hero-text-area centerd">
          <h1 class="hero-title  wow fadeInUp justify-content-center" data-wow-delay=".2s">{{ new.title }}</h1>
          <!-- <nav aria-label="breadcrumb ">
            <ul class="breadcrumb wow fadeInUp" data-wow-delay=".6s">
              <li class="breadcrumb-item"><a class="breadcrumb-link" href="#0"><i class="bi bi-house icon "></i>home</a></li>
              <li class="breadcrumb-item active">News / {{ new.title }}</li>
            </ul>
          </nav> -->
        </div>
      </div>
    </section>
    <br>
    <!-- End inner Page hero-->
    <!-- Start Project Details Area-->
    <section class="portfolio-single mega-section">
      <div class="container">
        {% comment %} <div class="featured-area">
          <div class="row">
            <div class="col-12  mx-auto">
              <div class="project-featured-img"><img class="featured-img " loading="lazy" src="{{ new.thumbnail.url }}" alt="{{ new.title }}"></div>
            </div>
          </div>
        </div> {% endcomment %}
        <div class="main-area">
          <div class="row">
            <div class="col-lg-8 col-lg-offset-4 ">
              <!-- <h5 class="sub-heading text-center">{{ new.title }}</h5> -->
              <div class="portfolio  portfolio-slider">
                <!--Swiper-->
                <div class="swiper-container wow fadeIn" data-wow-delay=".5s">
                  <div class="swiper-wrapper ">
                    <div class="">
                      <div class="item   "><a class="portfolio-img-link" href="#"><img class="portfolio-img   img-fluid featured-img" loading="lazy" src="{{ new.thumbnail.url }}" alt="{{ new.title }}"/></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- <hr> -->
              <p class="project-text">
                {{ new.body | safe }}
              </p>
              {% comment %} <hr> {% endcomment %}
              </div>
              <div class="portfolio  portfolio-slider">
                <!--Swiper-->
                {% for new in news %}
                {% if new %}
                <!-- <div class="swiper-container wow fadeIn" data-wow-delay=".5s">
                  <div class="swiper-wrapper ">
                    <div class="swiper-slide">
                      <div class="item   "><a class="portfolio-img-link" href="#"><img class="portfolio-img   img-fluid " loading="lazy" src="{{ new.banner.url }}" alt="{{ new.title }}"/></a>
                      </div>
                    </div>
                  </div>
                  <div class="swiper-button-prev">
                    <div class="left-arrow"><i class="bi bi-chevron-left icon "></i>
                    </div>
                  </div>
                  <div class="swiper-button-next">
                    <div class="right-arrow"><i class="bi bi-chevron-right icon "></i>
                    </div>
                  </div>
                </div> -->
                {% endif %}
                {% endfor %}
              </div>
            </div>
            <div class="col-12 col-lg-3  ">
              <div class="info-area">
                <div class="project-info">
                  <div class="row">
                    <!-- <div class="col-6 col-lg-12">
                      <div class="info">
                        <h5 class="title"> Publisher</h5>
                        <p class="detail">{{ new.publisher.first_name }} {{ new.publisher.last_name }}</p><i class="fas fa-address-card icon"></i>
                      </div>
                    </div> -->
                    <!-- <div class="col-6 col-lg-12">
                      <div class="info">
                        <h5 class="title">Category</h5>
                        {% if new.thematic_area == 0  %}
                        <p class="detail">General</p><i class="fas fa-tasks icon"></i>
                        {% endif %}
                        {% if new.thematic_area == 1  %}
                        <p class="detail">Health Care</p><i class="fas fa-tasks icon"></i>
                        {% endif %}
                        {% if new.thematic_area == 2  %}
                        <p class="detail">Agriculture and Environmental Conversation</p><i class="fas fa-tasks icon"></i>
                        {% endif %}
                        {% if new.thematic_area == 3  %}
                        <p class="detail">Infrastructure and Data Ecosystem</p><i class="fas fa-tasks icon"></i>
                        {% endif %}
                        {% if new.thematic_area == 4  %}
                        <p class="detail">Digital Economy and Small Scale Industry</p><i class="fas fa-tasks icon"></i>
                        {% endif %}
                      </div>
                    </div> -->
                    <div class="col-6 col-lg-12">
                      <div class="info">
                        <h5 class="title">Published on</h5>
                        <p class="detail"><i class="fas fa-calendar-alt icon"></i> {{ new.created_at | date }}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- <div class="cta-area"><a class=" btn-solid reveal-start" href="{% url 'news:news' %}">Back</a> -->
        </div>
        <br>
      </div>
    </section>
    <!-- End  Project Details Area-->
    <!-- End  take-action Section-->
   {% endblock %}