ai4ch/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth import views as auth_views
from ckeditor_uploader import views as ckeditor_views
from django.views.static import serve  
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('beans/detect/', include('beans.api_urls', namespace='beans-api-detect')), 
    path('cassava/detect/', include('cassava.api_urls', namespace='cassava-api-detect')), 
    path('maize/detect/', include('maize.api_urls', namespace='maize-api-detect')), 
    path('rice/detect/', include('rice.api_urls', namespace='rice-api-detect')), 
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    # Include Django browsable API
    path('auth-api/', include('rest_framework.urls', namespace='rest_framework')),
    # re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    # Application URLs
    path('', include('ai4chapp.urls')),
    path('users/', include('users.urls')),
    path('news/', include('news.urls', namespace='news')),
    path('beans/', include('beans.urls', namespace='beans')),   
    path('cassava/', include('cassava.urls', namespace='cassava')),
    path('maize/', include('maize.urls', namespace='maize')),
    path('rice/', include('rice.urls', namespace='rice')),
    path('reports/', include('reports.urls')),
    # Password reset views
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password/password_reset_complete.html'), name='password_reset_complete'),
    
    # Social authentication
    path('accounts/', include('allauth.urls')),
    
    # WYSIWYG editor
    path('tinymce/', include('tinymce.urls')),
    re_path(r'^ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    re_path(r'^ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

beans/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "beans"  

urlpatterns = [
    path('image-beans-desease-classifier',view=views.image_beans_classifier, name='image-beans-classifier'),
    path('image-beans-desease-detector',view=views.image_beans_detect, name='image-beans-detector'),
    path('video-beans-desease-detector',view=views.video_beans_detect, name='video-beans-detector'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maize/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "maize"  

urlpatterns = [
    path('predict/', view=views.MaizePredictImageView.as_view(), name='predict'),
    # path('detect/', view=views.MaizeDetectAPI.as_view(), name='detect'),
    path('image-maize-desease-classifier',view=views.image_maize_classifier, name='image-maize-classifier'),
    path('image-maize-desease-detector',view=views.image_maize_detect, name='image-maize-detector'),
    path('video-maize-desease-detector',view=views.video_maize_detect, name='video-maize-detector'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import NewsAPIView
from django.conf import settings
from django.conf.urls.static import static

app_name = "news"

urlpatterns = [
    path("", NewsAPIView.news, name='news'),
    path('add-new/', NewsAPIView.add_new, name="add-new"),
    path('news-list/review-new/publish-new/<int:id>', NewsAPIView.publish_new, name="publish-new"),
    path('news-list/publish-new/<int:id>', NewsAPIView.publish_new, name="publish-new"),
    path('news-list/review-new/<int:id>', NewsAPIView.review_new, name="review-new"),
    path('news-list/view-new/<int:id>/', NewsAPIView.view_new, name="view-new"),
    path('news-list/delete-new/<int:id>/', NewsAPIView.delete_new, name="delete-new"),
    path('news-list/', NewsAPIView.news_list, name="news-list"),
    path('news/<str:slug>/', NewsAPIView.read_new, name="read-new"),
    path('<str:slug>/', NewsAPIView.read_new, name="read-new"),
    path('api/news', NewsAPIView.as_view(), name="news-api"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rice/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "rice"  

urlpatterns = [
    path('predict/', view=views.RicePredictImageView.as_view(), name='predict'),
    # path('detect/', view=views.RiceDetectImageAPI.as_view(), name='detect'),
    path('image-rice-desease-classifier',view=views.image_rice_classifier, name='image-rice-classifier'),
    path('image-rice-desease-detector',view=views.image_rice_detect, name='image-rice-detector'),
    path('video-rice-desease-detector',view=views.video_rice_detect, name='video-rice-detector'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from users.views import UsersAPIView,MyTokenObtainPairView
from rest_framework_simplejwt.views import TokenRefreshView
from users import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"   

urlpatterns = [
    path('users/', UsersAPIView.as_view()),
    path('login_token/', MyTokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("logout/", views.logout_request, name= "logout"),
    path("login/", views.login_request, name="login"),
    path("change_password/", views.change_password, name="change-password"),
    path("update_info/", views.update_info, name="update-info"),
    path("add-staff/", views.add_staff, name="add-staff"),
    path("staffs/delete-staff/<int:id>", views.delete_staff, name="delete-staff"),
    path("staffs/deactivate-staff/<int:id>", views.deactivate_staff, name="deactivate-staff"),
    path("staffs/", views.staff_list, name="staffs"),
    path("register/", views.register_request, name="register"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('verify_phone/', views.VerifyUserAPIView.as_view(), name = 'verify_phone'),
    path('resend_code/<str:phone_number>/', views.resend_code, name='resend_code'),
    path('get-districts/', views.LocationAPIView().get_districts, name='get_districts'),
    path('get-wards/', views.LocationAPIView().get_wards, name='get_wards'),
    path('get-streets/', views.LocationAPIView().get_streets, name='get_streets'),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/backend/includes/base.html
{% include './header.html' %}
{% block content %}{% endblock %}
{% include './footer.html' %}

templates/backend/includes/footer.html
{% load static %}
       <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="{% static 'backend/assets/js/jquery-min.js' %}"></script>
      <script src="{% static 'backend/assets/js/popper.min.js' %}"></script>
      <script src="{% static 'backend/assets/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'backend/assets/js/jquery.app.js' %}"></script>
      <script src="{% static 'backend/assets/js/main.js' %}"></script>
  
    </body>
  </html>
    

templates/backend/includes/header.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AI4CroopHealth - Dashboard</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'backend/assets/css/bootstrap.min.css' %}">
    <!-- Fonts -->
    <link rel="stylesheet" type="text/css" href="{% static 'backend/assets/fonts/line-icons.css' %}">
    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="{% static 'backend/assets/plugins/morris/morris.css' %}">
    <!-- Main Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'backend/assets/css/main.css' %}">
    <!-- Responsive Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'backend/assets/css/responsive.css' %}">
    <style>
      /* Add this to your CSS */
    .language-switcher .dropdown-menu {
        min-width: 100px;
        padding: 0;
    }
    .language-switcher button {
        width: 100%;
        background: none;
        border: none;
        text-align: left;
        padding: 8px 15px;
    }
    </style>
  </head>
  <body>
    <div class="app header-default side-nav-dark">
      <div class="layout">
        <!-- Header START -->
        <div class="header navbar">
          <div class="header-container">
            <div class="nav-logo">
              <a href="{% url 'users:dashboard' %}">
                <b><img src="{% static 'backend/assets/img/logo.png' %}" alt=""></b>
                <!-- <span class="logo">
                  <img src="{% static 'backend/assets/img/logo-text.png' %}" alt="">
                </span> -->
              </a>
            </div>
            <ul class="nav-left">
              <li>
                <a class="sidenav-fold-toggler" href="javascript:void(0);">
                  <i class="lni-menu"></i>
                </a>
                <a class="sidenav-expand-toggler" href="javascript:void(0);">
                  <i class="lni-menu"></i>
                </a>
              </li>
            </ul>
            <ul class="nav-right">

            <!-- Language Switcher Dropdown -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  {% get_current_language as LANGUAGE_CODE %}
                  {{ LANGUAGE_CODE|upper }}
                  <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                  <form action="{% url 'set_language' %}" method="post">
                      {% csrf_token %}
                      <input type="hidden" name="next" value="{{ request.path }}">
                      <li>
                          <button type="submit" name="language" value="en">
                              {% trans "English" %}
                          </button>
                      </li>
                      <li>
                          <button type="submit" name="language" value="sw">
                              {% trans "Swahili" %}
                          </button>
                      </li>
                  </form>
              </ul>
          </li>

              <li class="user-profile dropdown dropdown-animated scale-left">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img class="profile-img img-fluid" src="{% static 'backend/assets/img/avatar/avatar.png' %}" alt=""> 
                </a>
                <ul class="dropdown-menu dropdown-md">
                  <li>
                    <ul class="list-media">
                      <li class="list-item avatar-info">
                        <div class="media-img">
                          <img src="{% static 'backend/assets/img/avatar/avatar.png' %}" alt="">
                        </div>
                        <div class="info">
                          <span class="title text-semibold">{{ user.first_name }} {{ user.last_name }}</span>
                          <span class="sub-title">{{ user.role }}</span>
                        </div>
                      </li>
                    </ul>
                  </li>
                  <li role="separator" class="divider"></li>
                  <!-- <li>
                    <a href="">
                      <i class="lni-cog"></i>
                      <span>Setting</span>
                    </a>
                  </li> -->
                  <!-- <li>
                    <a href="">
                      <i class="lni-user"></i>
                      <span>Profile</span>
                    </a>
                  </li> -->
                  <li>
                    <a href="{% url 'users:logout' %}">
                      <i class="lni-lock"></i>
                      <span>{% trans "Logout" %}</span>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
        <!-- Header END -->

        <!-- Side Nav START -->
        <div class="side-nav expand-lg">
          <div class="side-nav-inner">
            <ul class="side-nav-menu">
              <li class="side-nav-header">
                <span>{% trans "DASHBOARD" %}</span>
              </li>
              <li class="nav-item dropdown open">
                <a href="#" class="dropdown-toggle">
                  <span class="icon-holder">
                    <i class="lni-user"></i>
                  </span>
                  <span class="title">{% trans "Account" %}</span>
                  <span class="arrow">
                    <i class="lni-chevron-right"></i>
                  </span>
                </a>
                <ul class="dropdown-menu sub-down">
                  <li class="active">
                    <a href="{% url 'users:update-info' %}">{% trans "Update Info" %}</a>
                  </li>
                  <li>
                    <a href="{% url 'users:change-password' %}">{% trans "Change Password" %}</a>
                  </li>
                </ul>
              </li>
              {% if user.is_authenticed and user.role == 'admin' or user.is_superuser %}
              <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                    <span class="icon-holder">
                      <i class="lni-users"></i>
                    </span>
                    <span class="title">{% trans "Users" %}</span>
                    <span class="arrow">
                      <i class="lni-chevron-right"></i>
                    </span>
                  </a>
                <ul class="dropdown-menu sub-down">
                  <li>
                    <a href="{% url 'users:add-staff' %}">{% trans "Add Staff" %}</a>
                  </li>
                  <li>
                    <a href="{% url 'users:staffs' %}">{% trans "Staffs" %}</a>
                  </li>  
                </ul>
              </li>
              {% endif %}
              {% if user.is_authenticed and user.role == 'admin' or user.is_superuser %}
              <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                    <span class="icon-holder">
                      <i class="lni-dashboard"></i>
                    </span>
                    <span class="title">{% trans "Reports" %}</span>
                    <span class="arrow">
                      <i class="lni-chevron-right"></i>
                    </span>
                  </a>
                <ul class="dropdown-menu sub-down">
                  <li>
                    <a href="{% url 'reports:traffic' %}">{% trans "Traffic" %}</a>
                    <li>
                      <a href="{% url 'reports:analytics' %}">{% trans "Analytics" %}</a>
                    </li>
                  </li>
                </ul>
              </li>

              <!-- <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                  <span class="icon-holder">
                    <i class="lni-pencil"></i>
                  </span>
                  <span class="title">News</span>
                  <span class="arrow">
                    <i class="lni-chevron-right"></i>
                  </span>
                </a>
                <ul class="dropdown-menu sub-down">
                  <li>
                    <a href="{% url 'news:add-new' %}">Add News</a>
                  </li>
                  <li>
                    <a href="{% url 'news:news-list' %}">News List</a>
                  </li>
                </ul>
              </li> -->
              {% endif %}
              <!-- <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                  <span class="icon-holder">
                    <i class="lni-control-panel"></i>
                  </span>
                  <span class="title">Image Classification</span>
                  <span class="arrow">
                    <i class="lni-chevron-right"></i>
                  </span>
                </a>
                <ul class="dropdown-menu sub-down">
                  <li><a href="{% url 'beans:image-beans-classifier' %}">Beans</a></li>
                  <li><a href="{% url 'cassava:image-cassava-classifier' %}">Cassava</a></li>
                  <li><a href="{% url 'maize:image-maize-classifier' %}">Maize</a></li>
                  <li><a href="{% url 'rice:image-rice-classifier' %}">Rice</a></li>
                </ul>
              </li> -->

              <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                  <span class="icon-holder">
                    <i class="lni-control-panel"></i>
                  </span>
                  <span class="title">{% trans "Image Detection" %}</span>
                  <span class="arrow">
                    <i class="lni-chevron-right"></i>
                  </span>
                </a>
                <ul class="dropdown-menu sub-down">
                  <li><a href="{% url 'beans:image-beans-detector' %}">{% trans "Beans" %}</a></li>
                  <li><a href="{% url 'cassava:image-cassava-detector' %}">{% trans "Cassava" %}</a></li>
                  <li><a href="{% url 'maize:image-maize-detector' %}">{% trans "Maize" %}</a></li>
                  <li><a href="{% url 'rice:image-rice-detector' %}">{% trans "Rice" %}</a></li>
                </ul>
              </li>

              <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="#">
                  <span class="icon-holder">
                    <i class="lni-layers"></i>
                  </span>
                  <span class="title">{% trans "Video Detection" %}</span>
                  <span class="arrow">
                    <i class="lni-chevron-right"></i>
                  </span>
                </a>
                <ul class="dropdown-menu sub-down">
                  <li><a href="{% url 'beans:video-beans-detector' %}">{% trans "Beans" %}</a></li>
                  <li><a href="{% url 'cassava:video-cassava-detector' %}">{% trans "Cassava" %}</a></li>
                  <li><a href="{% url 'maize:video-maize-detector' %}">{% trans "Maize" %}</a></li>
                  <li><a href="{% url 'rice:video-rice-detector' %}">{% trans "Rice" %}</a></li>
                </ul>
              </li>

            </ul>
          </div>
        </div>
        <!-- Side Nav END -->